[listener]
type="agent"

[[port]]
port="tcp/8022"
services=["ssh-simulator"]

[service.ssh-simulator]
type="ssh-simulator"
credentials=["root:root", "root:password"]

[channel.console]
type="console"

[channel.elasticsearch]
type="elasticsearch"
url="https://192.168.1.103:9201/honeytrap"
username="es"
password="es2019!"
insecure=true

[[filter]]
channel=["console", "elasticsearch"]

[[logging]]
output = "stdout"
level = "debug"
